# Generated by Django 3.2 on 2021-05-24 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('extra_charges', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone_no', models.CharField(max_length=128)),
                ('in_time', models.DateTimeField(max_length=128)),
                ('out_time', models.DateTimeField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField(max_length=128)),
                ('phone_no', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('blood_group', models.CharField(max_length=128)),
                ('join_date', models.DateField(max_length=128)),
                ('avail_till', models.DateField(max_length=128)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgapp.preferencemodel')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgapp.visitormodel')),
            ],
        ),
    ]
