# Generated by Django 3.2 on 2021-05-24 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('fees', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('salary', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=128)),
                ('availablity', models.CharField(max_length=128)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgapp.roomtypemodel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgapp.staffmodel')),
            ],
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pgapp.roommodel'),
        ),
    ]
