# Generated by Django 3.2 on 2021-05-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0003_roommodel_room_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='avail_till',
            new_name='availed_till',
        ),
    ]
