# Generated by Django 3.2 on 2021-05-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0005_alter_studentmodel_visitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='visitor',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='visitor',
            field=models.ManyToManyField(blank=True, to='pgapp.VisitorModel'),
        ),
    ]
