# Generated by Django 3.2 on 2021-05-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0006_auto_20210525_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=128)),
                ('date', models.DateField(max_length=128)),
                ('status', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='fees',
            field=models.ManyToManyField(blank=True, to='pgapp.FeesModel'),
        ),
    ]
