# Generated by Django 3.2 on 2021-05-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0007_auto_20210525_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesmodel',
            name='date',
            field=models.DateTimeField(max_length=128),
        ),
    ]
