# Generated by Django 3.2 on 2021-05-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0008_alter_feesmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessFeesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=128)),
                ('date', models.DateTimeField(max_length=128)),
                ('status', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='mess_fees',
            field=models.ManyToManyField(blank=True, to='pgapp.MessFeesModel'),
        ),
    ]
